#!/usr/bin/env python3
"""
Inspect and validate all raw binary intensity dumps generated by Kotekan Beam Tracker pipelines.
Validates configurations: 64, 128, 256 Antennas across 4 beam slots.
"""

import sys
import glob
import os
import struct
import numpy as np

def inspect_binary_dump(file_path, n_time=15360, n_freq=336, max_beams=4):
    print("=" * 80)
    print(f" Inspecting Dump: {file_path}")
    print("=" * 80)
    
    if not os.path.exists(file_path):
        print(f"  [ERROR] File not found: {file_path}")
        return False
        
    expected_payload_bytes = n_time * n_freq * max_beams * 4
    file_size = os.path.getsize(file_path)
    
    with open(file_path, "rb") as f:
        meta_size_bytes = f.read(4)
        if len(meta_size_bytes) < 4:
            print("  [ERROR] File too small to contain metadata header")
            return False
        meta_size = struct.unpack("I", meta_size_bytes)[0]
        meta_data = f.read(meta_size)
        payload = f.read()
        
    actual_payload_bytes = len(payload)
    print(f"  Total File Size: {file_size:,} bytes | Header Size: {meta_size:,} bytes | Payload: {actual_payload_bytes:,} bytes")
    
    if actual_payload_bytes != expected_payload_bytes:
        print(f"  [ERROR] Payload mismatch! Actual={actual_payload_bytes}, Expected={expected_payload_bytes}")
        return False
        
    data = np.frombuffer(payload, dtype=np.float32)
    data = data.reshape((n_time, n_freq, max_beams))
    
    # Statistical validation
    n_nans = int(np.isnan(data).sum())
    n_infs = int(np.isinf(data).sum())
    n_negs = int((data < 0).sum())
    
    print(f"  Shape: {data.shape} (Time={n_time}, Freq={n_freq}, Beams={max_beams})")
    print(f"  Integrity: NaNs={n_nans}, Infs={n_infs}, Negatives={n_negs}")
    
    if n_nans > 0 or n_infs > 0 or n_negs > 0:
        print(f"  [ERROR] Data corrupted with NaNs/Infs/Negatives!")
        return False
        
    for b in range(max_beams):
        beam_data = data[:, :, b]
        b_min = float(np.min(beam_data))
        b_max = float(np.max(beam_data))
        b_mean = float(np.mean(beam_data))
        b_std = float(np.std(beam_data))
        print(f"  Beam Slot {b}: Min={b_min:.2f}, Max={b_max:.2f}, Mean={b_mean:.2f}, Std={b_std:.2f}")
        
    print(f"  [PASS] File {os.path.basename(file_path)} validated successfully.\n")
    return True

def main():
    dirs = [
        ("/tmp/test_charts_tracker", "64 Antennas"),
        ("/tmp/test_charts_tracker_128", "128 Antennas"),
        ("/tmp/test_charts_tracker_256", "256 Antennas"),
    ]
    
    all_ok = True
    for d, label in dirs:
        print(f"\n>>> Checking Output Dumps for {label} in {d} <<<")
        files = sorted(glob.glob(f"{d}/*.bin"))
        if not files:
            print(f"  No binary files found in {d}!")
            all_ok = False
            continue
        for f in files:
            ok = inspect_binary_dump(f)
            if not ok:
                all_ok = False
                
    if all_ok:
        print("\n" + "=" * 80)
        print(" ALL OUTPUT INTENSITY BINARY DUMPS ARE 100% VALID AND CLEAN!")
        print("=" * 80)
        sys.exit(0)
    else:
        print("\n" + "=" * 80)
        print(" SOME OUTPUT DUMPS FAILED VALIDATION!")
        print("=" * 80)
        sys.exit(1)

if __name__ == "__main__":
    main()
