#!/usr/bin/env python3
"""
Inspect & Visualize CHARTS 64-Antenna Correlator Dumps
=====================================================
Reads binary correlation matrix dumps generated by Kotekan's cudaCorrelatorAstron
(John Romein's Tensor Core Correlator), reconstructs the complete 64x64 Hermitian
visibility matrix V_ij for each frequency channel, verifies mathematical properties,
and exports diagnostic 2D heatmaps (|V_ij| and phase arg(V_ij)).
"""

from __future__ import annotations

import argparse
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def baseline_index(receiver_y: int, receiver_x: int) -> int:
    """Computes lower-triangular baseline index for (receiver_y, receiver_x)."""
    return receiver_y * (receiver_y + 1) // 2 + receiver_x


def load_astron_correlator_dump(
    bin_path: Path,
    num_elements: int = 64,
    num_channels: int = 336,
    polarizations: int = 2,
) -> np.ndarray:
    """
    Reads rawFileWrite binary file containing cudaCorrelatorAstron output.
    Returns:
        vis_cube: np.ndarray shape (num_channels, num_elements, num_elements) complex128
    """
    raw = np.fromfile(bin_path, dtype=np.uint8)
    if raw.size < 4:
        raise ValueError(f"File {bin_path} is smaller than 4-byte metadata header.")

    metadata_size = int(np.frombuffer(raw[:4].tobytes(), dtype="<u4", count=1)[0])
    payload_offset = 4 + metadata_size

    receiver_count = num_elements // polarizations
    num_baselines = receiver_count * (receiver_count + 1) // 2
    expected_ints = num_channels * num_baselines * polarizations * polarizations * 2
    expected_bytes = expected_ints * 4

    payload_size = raw.size - payload_offset
    if payload_size < expected_bytes:
        raise ValueError(
            f"File {bin_path} payload size {payload_size} bytes is less than expected {expected_bytes} bytes."
        )

    raw_ints = np.frombuffer(raw, dtype="<i4", count=expected_ints, offset=payload_offset)
    # Shape: (channels, baselines, pol_y, pol_x, 2)
    packed = raw_ints.reshape(num_channels, num_baselines, polarizations, polarizations, 2)
    c_data = packed[..., 0].astype(np.float64) + 1j * packed[..., 1].astype(np.float64)

    # Reconstruct full (channels, num_elements, num_elements) Hermitian matrix
    vis_cube = np.zeros((num_channels, num_elements, num_elements), dtype=np.complex128)

    for el_a in range(num_elements):
        rec_a, pol_a = divmod(el_a, polarizations)
        for el_b in range(num_elements):
            rec_b, pol_b = divmod(el_b, polarizations)
            if rec_b <= rec_a:
                b_idx = baseline_index(rec_a, rec_b)
                vis_cube[:, el_a, el_b] = c_data[:, b_idx, pol_a, pol_b]
            else:
                b_idx = baseline_index(rec_b, rec_a)
                vis_cube[:, el_a, el_b] = np.conj(c_data[:, b_idx, pol_b, pol_a])

    return vis_cube


def inspect_and_plot(
    bin_path: Path,
    output_plot: Path | None = None,
    num_elements: int = 64,
    num_channels: int = 336,
    freq_channel_idx: int = 168,
):
    """Inspects correlation dump and generates diagnostic multi-panel plots."""
    print(f"Reading correlator dump: {bin_path}")
    vis_cube = load_astron_correlator_dump(
        bin_path, num_elements=num_elements, num_channels=num_channels
    )

    # Select frequency slice
    v_slice = vis_cube[freq_channel_idx]  # shape (64, 64)
    v_amp = np.abs(v_slice)
    v_phase = np.angle(v_slice)

    # Diagonal: auto-correlations (antenna powers)
    auto_powers = np.diag(v_amp)

    # Hermitian check: || V - V^H ||_F / || V ||_F
    herm_diff = np.linalg.norm(v_slice - v_slice.conj().T)
    matrix_norm = np.linalg.norm(v_slice)
    herm_rel_err = herm_diff / (matrix_norm + 1e-12)

    # Cross-correlations: off-diagonal elements
    mask_off_diag = ~np.eye(num_elements, dtype=bool)
    mean_cross_amp = float(np.mean(v_amp[mask_off_diag]))
    max_cross_amp = float(np.max(v_amp[mask_off_diag]))
    mean_auto_power = float(np.mean(auto_powers))

    print("=" * 60)
    print(" Correlator Matrix Inspection Summary")
    print("=" * 60)
    print(f"  Dimensions               : {num_elements}x{num_elements} elements, {num_channels} channels")
    print(f"  Selected Frequency Bin   : Channel {freq_channel_idx}/{num_channels}")
    print(f"  Hermitian Symmetry Error : {herm_rel_err:.2e} (should be ~0.0)")
    print(f"  Mean Auto-Power (V_ii)   : {mean_auto_power:.2f}")
    print(f"  Min Auto-Power (V_ii)    : {np.min(auto_powers):.2f}")
    print(f"  Max Auto-Power (V_ii)    : {np.max(auto_powers):.2f}")
    print(f"  Mean Cross-Power (V_ij)  : {mean_cross_amp:.2f}")
    print(f"  Max Cross-Power (V_ij)   : {max_cross_amp:.2f}")
    print("=" * 60)

    # Create 3-panel diagnostic plot
    fig, axes = plt.subplots(1, 3, figsize=(18, 5.5))

    # Panel 1: Visibility Amplitude Matrix |V_ij|
    im0 = axes[0].imshow(v_amp, cmap="inferno", aspect="equal", origin="upper")
    axes[0].set_title(f"Visibility Amplitude |V_ij| (Ch {freq_channel_idx})", fontsize=12, fontweight="bold")
    axes[0].set_xlabel("Antenna j Index", fontsize=10)
    axes[0].set_ylabel("Antenna i Index", fontsize=10)
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04, label="Power")

    # Panel 2: Visibility Phase Matrix arg(V_ij)
    im1 = axes[1].imshow(v_phase, cmap="twilight", aspect="equal", origin="upper", vmin=-np.pi, vmax=np.pi)
    axes[1].set_title(f"Visibility Phase arg(V_ij) [rad] (Ch {freq_channel_idx})", fontsize=12, fontweight="bold")
    axes[1].set_xlabel("Antenna j Index", fontsize=10)
    axes[1].set_ylabel("Antenna i Index", fontsize=10)
    fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04, label="Radians")

    # Panel 3: Per-Antenna Auto-Power Profile V_ii
    axes[2].bar(np.arange(num_elements), auto_powers, color="steelblue", edgecolor="black", alpha=0.8)
    axes[2].axhline(mean_auto_power, color="red", linestyle="--", label=f"Mean: {mean_auto_power:.1f}")
    axes[2].set_title("Per-Antenna Auto-Correlations (V_ii)", fontsize=12, fontweight="bold")
    axes[2].set_xlabel("Antenna Index", fontsize=10)
    axes[2].set_ylabel("Auto Power", fontsize=10)
    axes[2].grid(True, linestyle=":", alpha=0.6)
    axes[2].legend(loc="upper right")

    plt.tight_layout()

    if output_plot:
        output_plot.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_plot, dpi=150)
        print(f"[SUCCESS] Saved diagnostic plot to: {output_plot}")
    plt.close()


def main():
    parser = argparse.ArgumentParser(description="Inspect CHARTS 64-Antenna Correlator Dumps")
    parser.add_argument("bin_file", type=str, help="Path to correlator output .bin file")
    parser.add_argument("--plot-out", type=str, default="", help="Path to save diagnostic PNG plot")
    parser.add_argument("--antennas", type=int, default=64, help="Number of antennas (default: 64)")
    parser.add_argument("--channels", type=int, default=336, help="Number of channels (default: 336)")
    parser.add_argument("--chan-idx", type=int, default=168, help="Channel index to display (default: 168)")
    args = parser.parse_args()

    bin_path = Path(args.bin_file)
    plot_path = Path(args.plot_out) if args.plot_out else None

    inspect_and_plot(
        bin_path=bin_path,
        output_plot=plot_path,
        num_elements=args.antennas,
        num_channels=args.channels,
        freq_channel_idx=args.chan_idx,
    )


if __name__ == "__main__":
    main()
