type: config
log_level: INFO
buffer_depth: 30 #max 1500 (RAM limit) (its important that if we are using GPU, this depth also affect to the VRAM)
cpu_affinity: [0,1]

num_elements: 32 #antennas
num_local_freq: 672 #Number of frequencies per data stream sent to each node.
n_channels_per_packet: 168
num_data_sets: 1 # Number of independent integrations within a single dataset
block_size: 2
num_blocks: 136 #(num_elements / block_size) * (num_elements / block_size + 1) / 2 #This is a kernel tuning parameter for a global work space dimension that sets data sizes fo  GPU work items.
packets_per_spectrum: 4
samples_per_data_set: 14976 # 49.920ms (one frame) 13/02/2026: SEEMS WE HAVE TO CHANGE IN ORDER TO FOLLOW THE KERNEL (MUST BE DIVISIBLE BY 32)
bytes_per_dataset: n_channels_per_packet * packets_per_spectrum * samples_per_data_set
sizeof_int: 4
data_format: "cuda_wmma"

main_pool:
  kotekan_metadata_pool: BasebandMetadata
  num_metadata_objects: buffer_depth*15

# Buffer to hold captured network packets
network_capture_buf:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: bytes_per_dataset * num_elements 
  numa_node: 0
  metadata_pool: main_pool
  zero_new_frames: true

mask_buffer_zeros:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: samples_per_data_set
  numa_node: 0
  metadata_pool: main_pool


host_correlation_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: num_local_freq * num_blocks * (block_size*block_size) * 2 * num_data_sets * sizeof_int 
    metadata_pool: main_pool


# DPDK Stage to capture network packets
dpdk:
  kotekan_stage: dpdkCore
  lcore_cpu_map: [3]
  main_lcore_cpu: 4
  lcore_port_map:
    - [0]
  max_rx_pkt_len: 9000
  num_mbufs: 9600
  handlers:
    - dpdk_handler: rfsocHandler 
      out_buffer: network_capture_buf
      alignment: 4000
      mask_buf: mask_buffer_zeros
      capture_n_frames: 20 # 1 frame =  49.920ms

zero_samples:
 kotekan_stage: zeroSamples
 out_buf: network_capture_buf
 lost_samples_buf: mask_buffer_zeros
 zero_value: 0
 sample_size: 21504 

gpu:
    profiling: false
    kernel_path: "lib/cuda/kernels"
    commands: &command_list
    - name: cudaInputData
      in_buf: host_voltage
      gpu_mem: voltage
    - name: cudaSyncInput
    - name: cudaShuffleAstron
      gpu_mem_voltage: voltage
      gpu_mem_ordered_voltage: ordered_voltage
    - name: cudaCorrelatorAstron
      gpu_mem_voltage: ordered_voltage
      gpu_mem_correlation_matrix: correlation_matrix
    - name: cudaSyncOutput
    - name: cudaOutputData
      in_buf: host_voltage # Metadata transfer from here
      gpu_mem: correlation_matrix
      out_buf: host_correlation
    gpu_0:
      kotekan_stage: cudaProcess
      gpu_id: 0 
      commands: *command_list
      in_buffers: 
        host_voltage: network_capture_buf
      out_buffers:
        host_correlation: host_correlation_buffer
      

# Monitoring stages 
# inspect_frame:
#   kotekan_stage: restInspectFrame
#   in_buf: network_capture_buf

inspect_frame2:
  kotekan_stage: restInspectFrame
  in_buf: host_correlation_buffer

# hexDump: # print hex dump of captured packets for debugging
#   kotekan_stage: hexDump
#   in_buf: host_correlation_buffer


raw_file_write:
  kotekan_stage: BasebandWriter
  samples_per_data_set: 10063872 # bytes_per_dataset 
  num_elements: 32 
  in_buf: network_capture_buf
  root_path: /data/32_test # Config (flag)
  dump_timeout: 1