########################
#### Global options ####
########################
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info  
cpu_affinity: [6, 7, 8, 9]

num_elements: 64
n_channels_per_packet: 168
local_subbands_per_packet: 2

buffer_depth: 110
baseband_buffer_depth: buffer_depth - 10

spectra_per_dataset: 15360 # 50 ms of data (one frame)
bytes_per_dataset: n_channels_per_packet * local_subbands_per_packet * spectra_per_dataset # 50 ms of data

# For basebandReadout
samples_per_data_set: 15360
capture_n_frames: 100



# Main CHARTS Metadata Pool
main_pool:
  kotekan_metadata_pool: chartsMetadata
  num_metadata_objects: 50

# Baseband metadata pool
baseband_pool:
  kotekan_metadata_pool: BasebandMetadata
  num_metadata_objects: 50

# Input data buffers from the DPDK stage
# Buffer to hold captured network packets
network_capture_buf_0:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: bytes_per_dataset * num_elements # 322.560.000 
  numa_node: 0
  metadata_pool: main_pool
  zero_new_frames: true

mask_buffer_zeros_0:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: spectra_per_dataset
  numa_node: 0
  metadata_pool: main_pool

# Additional buffers for the second NIC
network_capture_buf_1:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: bytes_per_dataset * num_elements # 322.560.000 
  numa_node: 0
  metadata_pool: main_pool
  zero_new_frames: true

mask_buffer_zeros_1:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: spectra_per_dataset
  numa_node: 0
  metadata_pool: main_pool

# baseband_output_buffer_0:
#   kotekan_buffer: standard
#   num_frames: baseband_buffer_depth
#   frame_size: bytes_per_dataset * num_elements
#   metadata_pool: baseband_pool

# baseband_output_buffer_1:
#   kotekan_buffer: standard
#   num_frames: baseband_buffer_depth
#   frame_size: bytes_per_dataset * num_elements
#   metadata_pool: baseband_pool

##########################
#### Pipeline Stages #####
##########################

# DPDK Stage to capture network packets
dpdk:
  kotekan_stage: dpdkCore
  lcore_cpu_map: [3, 5] # Use lcores 3 and 5 for DPDK processing
  main_lcore_cpu: 4 # Use lcore 4 for the main DPDK thread
  lcore_port_map: # Map lcores to network ports
    - [0] # lcore 3 handles port 0
    - [1] # lcore 5 handles port 1
  max_rx_pkt_len: 9000
  num_mbufs: 9600
  mbuf_data_size: 9216

  handlers:
    - dpdk_handler: rfsocHandlerShuffle
      out_buffer: network_capture_buf_0
      alignment: 15360
      mask_buf: mask_buffer_zeros_0
      first_subband: 0
      coarse_freq_start: 0
      num_local_freq: 336

    - dpdk_handler: rfsocHandlerShuffle
      out_buffer: network_capture_buf_1
      alignment: 15360
      mask_buf: mask_buffer_zeros_1
      first_subband: 2
      coarse_freq_start: 336
      num_local_freq: 336

zero_samples:
  kotekan_stage: zeroSamples
  out_buf: network_capture_buf_0
  lost_samples_buf: mask_buffer_zeros_0
  zero_value: 0
  sample_size: 21504

zero_samples_1:
  kotekan_stage: zeroSamples
  out_buf: network_capture_buf_1
  lost_samples_buf: mask_buffer_zeros_1
  zero_value: 0
  sample_size: 21504


# baseband_readout_0:
#   kotekan_stage: chartsBasebandReadout
#   in_buf: network_capture_buf_0
#   out_buf: baseband_output_buffer_0
#   mask_buf: mask_buffer_zeros_0
#   num_frames_buffer: buffer_depth - 10
#   max_dump_samples: samples_per_data_set * capture_n_frames

# baseband_readout_1:
#   kotekan_stage: chartsBasebandReadout
#   in_buf: network_capture_buf_1
#   out_buf: baseband_output_buffer_1
#   mask_buf: mask_buffer_zeros_1
#   num_frames_buffer: buffer_depth - 10
#   max_dump_samples: samples_per_data_set * capture_n_frames


# # Save baseband data
# baseband_save_0:
#   kotekan_stage: BasebandWriter
#   samples_per_data_set: 5160960 # bytes_per_dataset 
#   num_elements: 64 
#   in_buf: baseband_output_buffer_0
#   root_path: /data/32_test # Config (flag)
#   dump_timeout: 1
# ## Monitoring and debug stages ####

# baseband_save_1:
#   kotekan_stage: BasebandWriter
#   samples_per_data_set: 5160960 # bytes_per_dataset 
#   num_elements: 64 
#   in_buf: baseband_output_buffer_1
#   root_path: /data/32_test # Config (flag)
#   dump_timeout: 1


raw_file_write_0:
  kotekan_stage: rawFileWrite
  in_buf: network_capture_buf_0
  file_name: network_0
  base_dir: /data/32_test
  file_ext: bin
  num_frames_per_file: 1
  exit_after_n_files: 100

raw_file_write_1:
  kotekan_stage: rawFileWrite
  in_buf: network_capture_buf_1
  file_name: network_1
  base_dir: /data/32_test
  file_ext: bin
  num_frames_per_file: 1
  exit_after_n_files: 100
  
# inspect_frame:
#   kotekan_stage: restInspectFrame
#   in_buf: network_capture_buf_0

# inspect_frame_1:
#   kotekan_stage: restInspectFrame
#   in_buf: network_capture_buf_1