---
type: config
log_level: INFO
cpu_affinity: [0,1]

buffer_depth: 32
baseband_buffer_depth: buffer_depth - 10
capture_n_frames: 20

packets_per_frame: 20480
packet_payload_size: 5376
samples_per_data_set: 81920 # 20480 packets x 4 spectra/packet
num_elements: 1344 # 2 pol x 672 channels

# CPT frame_size: 81920 samples x 1344 bytes/sample = 110,100,480 bytes

main_pool:
  kotekan_metadata_pool: chartsMetadata
  num_metadata_objects: buffer_depth * 10

baseband_pool:
  kotekan_metadata_pool: BasebandMetadata
  num_metadata_objects: buffer_depth * 10

network_capture_buf:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: samples_per_data_set * num_elements
  numa_node: 0
  metadata_pool: main_pool
  zero_new_frames: true

mask_buffer_zeros:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: samples_per_data_set
  numa_node: 0
  metadata_pool: main_pool

baseband_output_buffer_0:
  kotekan_buffer: standard
  num_frames: baseband_buffer_depth
  frame_size: samples_per_data_set * num_elements
  numa_node: 0
  metadata_pool: baseband_pool

# DPDK Stage to capture CPT RFSoC packets.
dpdk:
  kotekan_stage: dpdkCore
  lcore_cpu_map: [3]
  main_lcore_cpu: 4
  lcore_port_map:
    - [0]
  max_rx_pkt_len: 9000
  num_mbufs: 9600
  handlers:
    - dpdk_handler: rfsocHandlerCPT
      out_buffer: network_capture_buf
      mask_buf: mask_buffer_zeros
      alignment: samples_per_data_set

zero_samples:
  kotekan_stage: zeroSamples
  out_buf: network_capture_buf
  lost_samples_buf: mask_buffer_zeros
  zero_value: 0
  sample_size: num_elements

baseband_readout:
  kotekan_stage: chartsBasebandReadout
  in_buf: network_capture_buf
  out_buf: baseband_output_buffer_0
  num_frames_buffer: buffer_depth - 10
  max_dump_samples: samples_per_data_set * capture_n_frames

inspect_frame:
  kotekan_stage: restInspectFrame
  in_buf: network_capture_buf

raw_file_write:
  kotekan_stage: BasebandWriter
  samples_per_data_set: samples_per_data_set
  num_elements: num_elements
  in_buf: baseband_output_buffer_0
  root_path: /data
  dump_timeout: 2
